version: '2.1'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --sql_mode="" --lower_case_table_names=1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=contato
    ports:
      - "3306:3306"